const cargo = require('../models/cargo') //model gestor

//gestor
exports.gestor = async (req, res) => {
    const {NOME, CPF, USUARIO_ID} = req.body
    let result = await cargo.gestor(NOME, CPF, USUARIO_ID)
    res.status(result.status).json(result.value)
}

//membro
exports.membro = async (req, res) =>{
    const {NOME, NATURALIDADE, IDENTIDADE, ESTADO_CIVIL, CPF, PROFISSAO, OCUPACAO, REF, NOME_PAI, NOME_MAE, NOME_CONJUGE, DATA_CONVERSAO, DATA_NASCIMENTO, DATA_BATISMO, DATA_BATISMO_ESP_SANTO,
    DATA_ADMISSAO, DATA_CANCELAMENTO, DATA_READMISSAO, LUGAR_CONGREGA, CLASSE_ESC_DOMINICAL, RUA, BAIRRO, NUMERO, COMPLEMENTO, PROCEDENCIA, MOTIVO_DESTINO, LUGAR_CONVERSAO, LUGAR_BATISMO,
    LUGAR_BATIMO_ESP_SANTO, ATIVIDADES_NA_IGREJA, CONGREGACAO_ID, USUARIO_ID} = req.body
    let result = await cargo.membro(NOME, NATURALIDADE, IDENTIDADE, ESTADO_CIVIL, CPF, PROFISSAO, OCUPACAO, REF, NOME_PAI, NOME_MAE, NOME_CONJUGE, DATA_CONVERSAO, DATA_NASCIMENTO, DATA_BATISMO, DATA_BATISMO_ESP_SANTO,
        DATA_ADMISSAO, DATA_CANCELAMENTO, DATA_READMISSAO, LUGAR_CONGREGA, CLASSE_ESC_DOMINICAL, RUA, BAIRRO, NUMERO, COMPLEMENTO, PROCEDENCIA, MOTIVO_DESTINO, LUGAR_CONVERSAO, LUGAR_BATISMO,
        LUGAR_BATIMO_ESP_SANTO, ATIVIDADES_NA_IGREJA, CONGREGACAO_ID, USUARIO_ID)
        res.status(result.status).json(result.value)
}